export const DEFAULT_INTERFACES = [
  {
    name: "btInterface",
    type: "SimpleBroadcastInterface",
    transmitSpeed: "250k",
    transmitRange: "10",
  },
  {
    name: "highspeedInterface",
    type: "SimpleBroadcastInterface",
    transmitSpeed: "10M",
    transmitRange: "200",
  },
];

export const DEFAULT_GROUPS = [
  // Static nodes  
  {
    groupID: "S",
    numHosts: 1,
    movementModel: "StationaryMovement",
    routeFile: "",
    routeType: 0,
    router: "CCNRouter",
    activeTimes: "0",
    messageTTL: "50",
  },
  {
    groupID: "S",
    numHosts: 1,
    movementModel: "StationaryMovement",
    routeFile: "",
    routeType: 0,
    router: "CCNRouter",
    activeTimes: "0",
    messageTTL: "50",
  },
  {
    groupID: "S",
    numHosts: 1,
    movementModel: "StationaryMovement",
    routeFile: "",
    routeType: 0,
    router: "CCNRouter",
    activeTimes: "0",
    messageTTL: "50",
  },
  {
    groupID: "S",
    numHosts: 1,
    movementModel: "StationaryMovement",
    routeFile: "",
    routeType: 0,
    router: "CCNRouter",
    activeTimes: "0",
    messageTTL: "50",
  },
  {
    groupID: "S",
    numHosts: 11,
    movementModel: "StationaryMovement",
    routeFile: "",
    routeType: 0,
    router: "CCNRouter",
    activeTimes: "0",
    messageTTL: "50",
  },
  // Mobile nodes
  {
    groupID: "p",
    numHosts: 20,
    movementModel: "ShortestPathMapBasedMovement",
    routeFile: "",
    routeType: 0,
    router: "CCNRouter",
    activeTimes: "0",
    messageTTL: "100",
  },
  {
    groupID: "c",
    numHosts: 10,
    movementModel: "ShortestPathMapBasedMovement",
    routeFile: "",
    routeType: 0,
    router: "CCNRouter",
    activeTimes: "0",
    messageTTL: "100",
  },
  // Trams
  {
    groupID: "t",
    numHosts: 10,
    movementModel: "MapRouteMovement",
    routeFile: "data/tram3.wkt",
    routeType: 1,
    router: "CCNRouter",
    activeTimes: "0",
    messageTTL: "150",
  },
  {
    groupID: "t",
    numHosts: 20,
    movementModel: "MapRouteMovement",
    routeFile: "data/tram4.wkt",
    routeType: 2,
    router: "CCNRouter",
    activeTimes: "0",
    messageTTL: "150",
  },
  {
    groupID: "t",
    numHosts: 10,
    movementModel: "MapRouteMovement",
    routeFile: "data/tram10.wkt",
    routeType: 2,
    router: "CCNRouter",
    activeTimes: "0",
    messageTTL: "150",
  },
  // Walkers / extra pedestrians
  {
    groupID: "w",
    numHosts: 10,
    movementModel: "ShortestPathMapBasedMovement",
    routeFile: "",
    routeType: 0,
    router: "CCNRouter",
    activeTimes: "0",
    messageTTL: "150",
  },
  {
    groupID: "p",
    numHosts: 15,
    movementModel: "ShortestPathMapBasedMovement",
    routeFile: "",
    routeType: 0,
    router: "CCNRouter",
    activeTimes: "0",
    messageTTL: "150",
  },
];
