export const DEFAULT_INTERFACES = [
  {
    name: "btInterface",
    type: "SimpleBroadcastInterface",
    transmitSpeed: "250k",
    transmitRange: "10",
  },
  {
    name: "highspeedInterface",
    type: "SimpleBroadcastInterface",
    transmitSpeed: "10M",
    transmitRange: "200",
  },
];

export const DEFAULT_GROUPS = [
  {
    groupID: "S",
    numHosts: 1,
    movementModel: "StationaryMovement",
    applicationType: "Producer",
    interface1: "highspeedInterface",
    bufferSize: "1G",
    speed: "0,0",
    nodeLocation: "2600,2200",
    routeFile: "",
    routeType: 0,
    waitTime: "",
    okMaps: "",
    activeTimes: "0",
    messageTTL: "50",
  },
  {
    groupID: "S",
    numHosts: 1,
    movementModel: "StationaryMovement",
    applicationType: "Producer",
    interface1: "highspeedInterface",
    bufferSize: "1G",
    speed: "0,0",
    nodeLocation: "1300,500",
    routeFile: "",
    routeType: 0,
    waitTime: "",
    okMaps: "",
    activeTimes: "0",
    messageTTL: "50",
  },
  {
    groupID: "S",
    numHosts: 1,
    movementModel: "StationaryMovement",
    applicationType: "Producer",
    interface1: "highspeedInterface",
    bufferSize: "1G",
    speed: "0,0",
    nodeLocation: "2314,1283",
    routeFile: "",
    routeType: 0,
    waitTime: "",
    okMaps: "",
    activeTimes: "0",
    messageTTL: "50",
  },
  {
    groupID: "S",
    numHosts: 1,
    movementModel: "StationaryMovement",
    applicationType: "Producer",
    interface1: "highspeedInterface",
    bufferSize: "1G",
    speed: "0,0",
    nodeLocation: "2800,750",
    routeFile: "",
    routeType: 0,
    waitTime: "",
    okMaps: "",
    activeTimes: "0",
    messageTTL: "50",
  },
  {
    groupID: "S",
    numHosts: 11,
    movementModel: "StationaryMovement",
    applicationType: "Producer",
    interface1: "highspeedInterface",
    bufferSize: "1G",
    speed: "0,0",
    nodeLocation: "1400,1600",
    routeFile: "",
    routeType: 0,
    waitTime: "",
    okMaps: "",
    activeTimes: "0",
    messageTTL: "50",
  },
  {
    groupID: "p",
    numHosts: 20,
    movementModel: "ShortestPathMapBasedMovement",
    applicationType: "Consumer",
    interface1: "btInterface",
    bufferSize: "",
    speed: "",
    nodeLocation: "",
    routeFile: "",
    routeType: 0,
    waitTime: "",
    okMaps: "",
    activeTimes: "0",
    messageTTL: "100",
  },
  {
    groupID: "c",
    numHosts: 10,
    movementModel: "ShortestPathMapBasedMovement",
    applicationType: "Intermedia",
    interface1: "btInterface",
    bufferSize: "50M",
    speed: "2.7,13.9",
    nodeLocation: "",
    routeFile: "",
    routeType: 0,
    waitTime: "",
    okMaps: "1",
    activeTimes: "0",
    messageTTL: "100",
  },
  {
    groupID: "t",
    numHosts: 10,
    movementModel: "MapRouteMovement",
    applicationType: "Intermedia",
    interface1: "btInterface",
    bufferSize: "50M",
    speed: "2.5,5",
    nodeLocation: "",
    routeFile: "data/tram3.wkt",
    routeType: 1,
    waitTime: "10,30",
    okMaps: "",
    activeTimes: "0",
    messageTTL: "150",
  },
  {
    groupID: "t",
    numHosts: 20,
    movementModel: "MapRouteMovement",
    applicationType: "Intermedia",
    interface1: "btInterface",
    bufferSize: "50M",
    speed: "7,10",
    nodeLocation: "",
    routeFile: "data/tram4.wkt",
    routeType: 2,
    waitTime: "10,30",
    okMaps: "",
    activeTimes: "0",
    messageTTL: "150",
  },
  {
    groupID: "t",
    numHosts: 10,
    movementModel: "MapRouteMovement",
    applicationType: "Intermedia",
    interface1: "btInterface",
    bufferSize: "50M",
    speed: "7,10",
    nodeLocation: "",
    routeFile: "data/tram10.wkt",
    routeType: 2,
    waitTime: "10,30",
    okMaps: "",
    activeTimes: "0",
    messageTTL: "150",
  },
  {
    groupID: "w",
    numHosts: 10,
    movementModel: "ShortestPathMapBasedMovement",
    applicationType: "Consumer",
    interface1: "btInterface",
    bufferSize: "",
    speed: "",
    nodeLocation: "",
    routeFile: "",
    routeType: 0,
    waitTime: "",
    okMaps: "",
    activeTimes: "0",
    messageTTL: "150",
  },
  {
    groupID: "p",
    numHosts: 15,
    movementModel: "ShortestPathMapBasedMovement",
    applicationType: "Producer",
    interface1: "btInterface",
    bufferSize: "",
    speed: "",
    nodeLocation: "",
    routeFile: "",
    routeType: 0,
    waitTime: "",
    okMaps: "",
    activeTimes: "0",
    messageTTL: "150",
  },
];
